config/routes.rb
Rails.application.routes.draw do
  root 'documents#index'

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get  '/logout', to: 'sessions#destroy'

  get  '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :users

  resources :documents, only: [:index, :show] do
    resources :fragments,  only: [:index, :show]
  end

  namespace :admin do
    resources :documents do
      resources :fragments
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id           :bigint           not null, primary key
#  access_level :integer
#  note         :string
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Document < ApplicationRecord
  has_many :fragments, -> { order(position: :asc) }

  enum access_level: Role.tiers
end

app/models/fragment.rb
# == Schema Information
#
# Table name: fragments
#
#  id             :bigint           not null, primary key
#  classes        :string           default(""), not null
#  data           :string           default(""), not null
#  element        :string           default("p"), not null
#  meta           :string           default("")
#  parent_classes :string           default(""), not null
#  position       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  document_id    :bigint
#
# Indexes
#
#  index_fragments_on_document_id  (document_id)
#
class Fragment < ApplicationRecord
  include ActionView::Helpers

  belongs_to :document
  has_many_attached :images, dependent: :purge_later

  acts_as_list scope: :document

  MD_MAPPING = {
    "h1" => "# %{data}",
    "h2" => "## %{data}",
    "h3" => "### %{data}",
    "p" => "%{data}",
    "ol" => "%{data}",
    "ul" => "%{data}",
    "pre" => "```%{meta}\n%{data}\n```",
    "image" => "![%{meta}](%{data} '%{classes}_%{parent_classes}')"
  }.freeze

  def to_md
    if element == 'image'
      path = Rails.application.routes.url_helpers.rails_blob_path(images.first.blob, only_path: true)
      MD_MAPPING[element] % {data: path, meta: meta, classes: classes, parent_classes: parent_classes}
    else
      MD_MAPPING[element] % {data: data, meta: meta}
    end
  end

  def render
    MarkdownRenderer.md_to_html(self.to_md)
  end
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id           :bigint           not null, primary key
#  display_name :string
#  tier         :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Role < ApplicationRecord
  has_many :users
  enum tier: { public_user: 1, tier1: 10, tier2: 20, admin: 30 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  role_id         :bigint
#
# Indexes
#
#  index_users_on_role_id  (role_id)
#
class User < ApplicationRecord
  has_secure_password

  belongs_to :role
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController
  before_action :logged_in?
  before_action :set_document, only: %i[ show edit update destroy markdown]

  def index
    @documents = Document.all.order(:access_level)
  end

  def create
    @document = Document.new(document_params)
    @document.save

    render turbo_stream: turbo_stream.after(
        "new-doc",
        partial: "documents/document",
        locals: { document: @document }
      )
  end

  def update
    if @document.update(document_params)
      render turbo_stream: turbo_stream.update(@document)
    end
  end

  def destroy
    @document.destroy
    render turbo_stream: turbo_stream.remove("document_#{@document.id}")
  end

  def show
    @document
  end
  private
  
  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :note, :access_level)
  end
end

app/controllers/admin/fragments_controller.rb
class Admin::FragmentsController < ApplicationController
  before_action :set_document
  before_action :set_fragment, only: [:update, :destroy]

  def update
    @fragment.update(fragment_params.except(:images))

    render @fragment
  end

  def create
    @fragment = @document.fragments.build(fragment_params.except(:dom_id))
    @fragment.save
    @dom_id = fragment_params[:dom_id]

    redirect_to(admin_document_path(@document, anchor: @dom_id))
  end

  def destroy
    @fragment.destroy
    render turbo_stream: turbo_stream.remove(@fragment)
  end

  private

  def set_fragment
    @fragment = @document.fragments.find(params[:id])
  end

  def set_document
    @document = Document.find(params[:document_id])
  end

  def fragment_params
    params.require(:fragment).permit(:element, :data, :meta, :position, :dom_id, :classes, :parent_classes, images: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_role
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_role
    @current_role ||= current_user&.role || Role.find_by(tier: :public_user)
  end

  def current_access_level_names
    tiers = Role.tiers
    tiers.filter{ |k,v| v <= tiers[current_role.tier] }.keys
  end

  def logged_in?
    unauthorized unless current_user&.role&.admin? && session[:user_id] == current_user.id
  end

  def unauthorized
    @current_user = nil
    reset_session
    redirect_to login_path
  end
end

app/controllers/document_controller.rb
class DocumentController < ApplicationController
  def index
    @fragments = Fragment.all.order(position: :asc)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.where(access_level: current_access_level_names)
    render :index
  end

  def show
    @document = Document.find_by(id: params[:id])
    render :show
  end
end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController
  before_action :set_document
  before_action :set_fragment, only: [:update, :destroy]

  def update
    @fragment.update(fragment_params.except(:images))

    render @fragment
  end

  def create
    @fragment = @document.fragments.build(fragment_params.except(:dom_id))
    @fragment.save
    @dom_id = fragment_params[:dom_id]

    redirect_to(document_path(@document, anchor: @dom_id))
  end

  def destroy
    @fragment.destroy
    render turbo_stream: turbo_stream.remove(@fragment)
  end

  private

  def set_fragment
    @fragment = @document.fragments.find(params[:id])
  end

  def set_document
    @document = Document.find(params[:document_id])
  end

  def fragment_params
    params.require(:fragment).permit(:element, :data, :meta, :position, :dom_id, :classes, :parent_classes, images: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = 'Successfully Logged In!'
      redirect_to documents_path
    else
      reset_session
      flash[:warning] = 'Invalid Username or Password'
      redirect_to '/login'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Success'
      redirect_to documents_path
    else
      flash[:warning] = 'Uh oh'
      redirect_to '/register'
    end
  end
  def show
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/fragments_helper.rb
module FragmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/documents/_document.html.erb
<%= turbo_frame_tag dom_id(document) do %>
  <div class="card doc_card">
    <div class="card-body">
      <h5 class="card-title"><%= document.title %></h5>
      <p class="card-text"><%= document.note %></p>
      <%= link_to 'Edit This Document', admin_document_path(document), target: '_top', class: 'btn btn-primary' %>
    </div>
      <%= form_with model: [:admin, document] do |form| %>
        <%= form.select :access_level, Document.access_levels.keys, selected: document.access_level %>
        <%= form.submit 'Submit' %>
      <% end %>
      <%= link_to(
        admin_document_path(document),
        method: :delete,
        data: {
          turbo_method: :delete,
          turbo_frame: :documents
        },
        hidden: false
        ) do  %>
        <i class="fa fa-trash red float-end"></i>
        <% end%>
  </div>
<% end %>

app/views/admin/documents/_form.html.erb
<div class='mb-3 doc_form'>
<%= form_with model: [:admin, document] do |form| %>
  <%= form.label :title, class: 'form-label float-start' %>
  <%= form.text_field :title, id: :title, class: 'form-control' %>
  <%= form.label :note, class: 'form-label float-start' %>
  <%= form.text_field :note, id: :note, class: 'form-control' %>
  <%= form.label :access_level, class: 'form-label float-start' %>
  <%= form.select :access_level, Role.tiers, id: :note, class: 'form-control' %>
  <%= form.submit 'Create', class: 'btn btn-secondary mt-3', data: {'controller': 'add-doc', 'action': 'click->add-doc#save'} %>
  <%= form.button 'Cancel', class: 'btn btn-secondary mt-3', data: {'controller': 'add-doc', 'action': 'click->add-doc#cancelNewCard'} %>
<% end %>
</div>

app/views/admin/documents/index.html.erb
<%= turbo_frame_tag "documents", class: 'card_grid' do %>
  <%= turbo_frame_tag "new-doc", class: "card doc_card" do %>
    <div class="card-body">
      <h5>Add New Document</h5>
        <div data-controller="add-doc" data-action="click->add-doc#showNewCard">
          <i id="add_new_doc_btn" class="fa fa-plus"></i>
          <div id="form_wrapper" class="hiddenn">
            <%= render partial: 'admin/documents/form', locals: { document: Document.new} %>
          </div>
        </div>
    </div>
  <% end %>

  <% @documents.each do |doc| %>
    <%= render partial: 'admin/documents/document', locals: { document: doc } %>
  <% end %>
<% end %>

app/views/admin/documents/show.html.erb
<div id="doc_grid">
  <aside class="js-toc">
  </aside>
  <main class="section">
  <div id="document_header"class="bg-secondary mb-5 p-3 container-fluid">
    <h1>Title: <%= @document.title %></h1>
    <h5>Notes: <%= @document.note %></h5>
  </div>
    <div class="article container">
      <div class="fragments-container" data-controller="sortable">
      <% if @document.fragments.present? %>
        <% @document.fragments.each do |fragment| %>
          <%= render fragment %>
        <% end %>
      <% else %>
        <%= render "admin/fragments/new", position: 0, dom_id: dom_id(Fragment.new) %>
      <% end %>
      </div>
    </div>
  </main>
</div>

app/views/admin/fragments/_button_container.html.erb
<% is_image = fragment.element == 'image' %>
<% menu = is_image ? 'showImageMenu' : 'showMenu' %>
<div class="fragment-button-container" data-form-id="fragment_<%= fragment.id %>_form">
  <button class="btn btn-secondary change_frag_menu_btn"
    data-action='click->change-fragment#<%= menu %>'>
    <i class="fa-solid fa-gear"></i>
  </button>
  <button class="btn btn-secondary sortable-handle">
    <i class="fa fa-up-down"></i>
  </button>
</div>

app/views/admin/fragments/_fragment.html.erb
<div class="draggable_fragment">
  <%= turbo_frame_tag dom_id(fragment) do %>

    <div class="fragment-wrapper <%= fragment.element %>" data-controller="change-fragment">
      <%= render partial: 'admin/fragments/button_container', locals: { fragment: fragment} %>
      <div class="fragment <%= fragment.element %>"
          data-controller="editable"
          data-action="
          click->editable#click
          blur->editable#blur
          keydown->editable#keyDown
          mouseup->editable#mouseUp
          mousedown->editable#mouseDown">
          <%= fragment.render %>

        <%= form_with model: [:admin, @document, fragment], class: 'change-fragment-form', id: "fragment_#{fragment.id}_form" do |form| %>
          <%= form.text_field :data, id: :data, hidden: true %>
          <%= form.text_field :classes, id: :classes, hidden: true %>
          <%= form.text_field :parent_classes, id: :parent_classes, hidden: true %>
          <%= form.text_field :element, id: :element, hidden: true %>
          <%= form.text_field :meta, id: :meta, hidden: true %>
          <%= form.number_field :position, id: :position, hidden: true %>
          <%= form.file_field :images, id: :images, multiple: true, accept: 'image/png,image/gif,image/jpeg', hidden: true %>
          <%= form.submit hidden: true %>
        <% end %>
      </div>
      <%= button_to 'delete', [:admin, @document, fragment], hidden: true, class: 'delete_link', method: :delete %>
    </div>
  <% end %>
  <%= render "admin/fragments/new", position: fragment.position, dom_id: dom_id(fragment) %>
</div>

app/views/admin/fragments/_new.html.erb
<div class="add-fragment" data-controller="add-fragment">
  <div class="add-fragment-button-container">
    <%= form_with(
      model: [:admin, @document, Fragment.new(
        element: "p",
        data: "edit me",
        position: (position + 1))], class: 'add-fragment-form') do |form| %>
      <%= form.text_field :data, hidden: true %>
      <%= form.text_field :element, hidden: true %>
      <%= form.text_field :meta, hidden: true %>
      <%= form.text_field :position, hidden: true %>
      <%= form.hidden_field :dom_id, value: dom_id %>
      <%= form.file_field :images, id: :images, multiple: true, accept: 'image/png,image/gif,image/jpeg', hidden: true, data: { action: "change->add-fragment#submitImages"} %>
      <%= form.submit("Create", hidden: true, data: { turbo: false }) %>
      <button
        class="button is-link is-round is-small"
        data-action="click->add-fragment#showMenu">
        <i class="fa fa-plus"></i>
      </button>
    <% end %>
  </div>
  <hr class="add-fragment-indicator"></hr>
</div>

app/views/document/index.html.erb
<section class="section">
  <div class="article container">
    <% @fragments.each do |fragment| %>
      <%= render fragment %>
    <% end %>
  </div>
</section>

app/views/documents/_document.html.erb
  <div class="card doc_card">
    <div class="card-body">
      <h5 class="card-title"><%= document.title %></h5>
      <p class="card-text"><%= document.note %></p>
      <%= link_to 'View This Document', document_path(document), target: '_top', class: 'btn btn-primary' %>
    </div>
  </div>

app/views/documents/_form.html.erb
<div class='mb-3 doc_form'>
<%= form_with model: document do |form| %>
  <%= form.label :title, class: 'form-label float-start' %>
  <%= form.text_field :title, id: :title, class: 'form-control' %>
  <%= form.label :note, class: 'form-label float-start' %>
  <%= form.text_field :note, id: :note, class: 'form-control' %>
  <%= form.submit 'Create', class: 'btn btn-secondary mt-3', data: {'controller': 'add-doc', 'action': 'click->add-doc#save'} %>
  <%= form.button 'Cancel', class: 'btn btn-secondary mt-3' %>
<% end %>
</div>

app/views/documents/index.html.erb
<%= turbo_frame_tag "documents", class: 'card_grid' do %>
    <% @documents.each do |doc| %>
      <%= render partial: 'documents/document', locals: { document: doc } %>
    <% end %>
  <% end %>
</div>

app/views/documents/show.html.erb
<div id="doc_grid">
  <aside class="js-toc">
  </aside>
  <main class="section">
  <div id="document_header"class="bg-secondary mb-5 p-3 container-fluid">
    <h1>Title: <%= @document.title %></h1>
    <h5>Notes: <%= @document.note %></h5>
  </div>
    <div class="article container">
      <div class="fragments-container" data-controller="sortable">
      <% if @document.fragments.present? %>
        <% @document.fragments.each do |fragment| %>
          <%= render fragment %>
        <% end %>
      <% end %>
      </div>
    </div>
  </main>
</div>

app/views/fragments/_fragment.html.erb
<div class="draggable_fragment">
  <%= turbo_frame_tag dom_id(fragment) do %>
    <div class="fragment-wrapper <%= fragment.element %>" data-controller="change-fragment">
      <div class="fragment <%= fragment.element %>">
          <%= fragment.render %>
      </div>
    </div>
  <% end %>
</div>

app/views/fragments/_new.html.erb
<div class="add-fragment" data-controller="add-fragment">
  <div class="add-fragment-button-container">
    <%= form_with(
      model: [@document, Fragment.new(
        element: "p",
        data: "edit me",
        position: (position + 1))], class: 'add-fragment-form') do |form| %>
      <%= form.text_field :data, hidden: true %>
      <%= form.text_field :element, hidden: true %>
      <%= form.text_field :meta, hidden: true %>
      <%= form.text_field :position, hidden: true %>
      <%= form.hidden_field :dom_id, value: dom_id %>
      <%= form.file_field :images, id: :images, multiple: true, accept: 'image/png,image/gif,image/jpeg', hidden: true, data: { action: "change->add-fragment#submitImages"} %>
      <%= form.submit("Create", hidden: true, data: { turbo: false }) %>
      <button
        class="button is-link is-round is-small"
        data-action="click->add-fragment#showMenu">
        <i class="fa fa-plus"></i>
      </button>
    <% end %>
  </div>
  <hr class="add-fragment-indicator"></hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyDocs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav id="header" class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand ms-5" href="#">EasyDocs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active' %>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Admin', admin_documents_path, class: 'nav-link active' if current_user.role.admin? %>
        </li>
        <% end %>
        <li class="nav-item">
          <% if current_user %>
            <%= link_to 'LogOut', logout_path, class: 'nav-link active' %>
          <% else %>
            <%= link_to 'Login', login_path, class: 'nav-link active' %>
          <% end %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<div class="container">
  <%= form_with model: @user, method: :post do |form| %>
    <div class="form-group">
      <%= form.label :name, "Name:" %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :email, "Email:" %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :password, "Password:" %>
      <%= form.text_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation, "Password Confirmation:" %>
      <%= form.text_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= form.submit "Search", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>